name: 🚀 Build and Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🔽 Download project
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 🏠 Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: 👷‍♂️ Install dependencies
        run: |
          npm ci

      - name: 🔅 Prettier, Code Syntax Standard
        run: |
          echo "Recuerda tener instalado Prettier como formateador de código en tu Editor de texto"
          echo "Este código usará como estándar la indentación de Prettier."
          echo "Para solucionar tu indentación, ejecuta npm run sintax:fix"
          npm run sintax:test

      # - name: 👀 Project Standards
      #   run: |
      #     npm test

      - name: 👀 Code Quality
        run: |
          echo "Se revisará la calidad del código para que la consola no tenga warnings ni errores."
          echo "Se validará que no existan variables sin usar, console.logs, malos estándares de código, etc."
          npm run lint

      - name: 📦 Build project
        run: |
          npm run build

      - name: 🚀 Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
